"""Offline generator for scaffold/pokerbot/core/preflop_tables.py (dev only).

Computes, by Monte Carlo with the bot's own evaluator:
  EQ_VS_RANDOM[c][k-1]  equity of class c vs k random hands, k = 1..5
  HAND_ORDER            classes ordered strongest first (blend of HU and 3-way equity)
  EQ_VS_TOP[c][b]       heads-up equity of class c vs the top x% range, x = 2*(b+1)

Usage:  python tools/gen_preflop_tables.py [--samples N] [--top-samples M]
"""

from __future__ import annotations

import argparse
import random
import sys
from multiprocessing import Pool
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scaffold"))

from pokerbot.core.cards import COMBOS, COMBO_CLASS, class_combos, class_name  # noqa: E402
from pokerbot.core.evaluator import evaluate  # noqa: E402

CLASS_COMBOS = [[c for c, k in zip(COMBOS, COMBO_CLASS) if k == idx] for idx in range(169)]
TOP_BUCKETS = 50


def _eq_vs_random(args):
    cls, k, samples, seed = args
    rng = random.Random(seed)
    won = 0.0
    for _ in range(samples):
        a, b = rng.choice(CLASS_COMBOS[cls])
        deck = [c for c in range(52) if c != a and c != b]
        draw = rng.sample(deck, 5 + 2 * k)
        board = draw[:5]
        mine = evaluate([a, b, *board])
        best = 0
        ties = 0
        for j in range(k):
            v = evaluate([draw[5 + 2 * j], draw[6 + 2 * j], *board])
            if v > best:
                best, ties = v, 1
            elif v == best:
                ties += 1
        if mine > best:
            won += 1.0
        elif mine == best:
            won += 1.0 / (ties + 1)
    return cls, k, won / samples


def top_range_weights(order: list[int], pct: float) -> list[float]:
    """Per-combo weights for the top `pct` (0..1) of hands by `order`."""
    target = pct * 1326
    class_w = [0.0] * 169
    total = 0.0
    for cls in order:
        n = class_combos(cls)
        if total + n <= target:
            class_w[cls] = 1.0
            total += n
        else:
            class_w[cls] = max(0.0, (target - total) / n)
            break
    return [class_w[k] for k in COMBO_CLASS]


def _eq_vs_top(args):
    cls, bucket, order, samples, seed = args
    rng = random.Random(seed)
    weights = top_range_weights(order, 2 * (bucket + 1) / 100)
    pool = [(c, w) for c, w in zip(COMBOS, weights) if w > 0]
    combos = [c for c, _ in pool]
    cum = []
    acc = 0.0
    for _, w in pool:
        acc += w
        cum.append(acc)
    won = 0.0
    done = 0
    while done < samples:
        a, b = rng.choice(CLASS_COMBOS[cls])
        # rejection-sample a non-conflicting opponent combo from the range
        for _ in range(50):
            o1, o2 = combos[_bisect(cum, rng.random() * acc)]
            if o1 not in (a, b) and o2 not in (a, b):
                break
        else:
            continue
        deck = [c for c in range(52) if c not in (a, b, o1, o2)]
        board = rng.sample(deck, 5)
        m = evaluate([a, b, *board])
        o = evaluate([o1, o2, *board])
        won += 1.0 if m > o else 0.5 if m == o else 0.0
        done += 1
    return cls, bucket, won / samples


def _bisect(cum, x):
    lo, hi = 0, len(cum) - 1
    while lo < hi:
        mid = (lo + hi) // 2
        if cum[mid] < x:
            lo = mid + 1
        else:
            hi = mid
    return lo


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--samples", type=int, default=20000)
    ap.add_argument("--top-samples", type=int, default=4000)
    args = ap.parse_args()

    with Pool() as pool:
        jobs = [(c, k, args.samples, c * 10 + k) for c in range(169) for k in range(1, 6)]
        eq_random = [[0.0] * 5 for _ in range(169)]
        for cls, k, eq in pool.imap_unordered(_eq_vs_random, jobs, chunksize=8):
            eq_random[cls][k - 1] = eq

        def pct_rank(values):
            order = sorted(range(169), key=lambda c: values[c])
            ranks = [0.0] * 169
            for i, c in enumerate(order):
                ranks[c] = i / 168
            return ranks

        r1 = pct_rank([e[0] for e in eq_random])
        r3 = pct_rank([e[2] for e in eq_random])
        order = sorted(range(169), key=lambda c: -(0.5 * r1[c] + 0.5 * r3[c]))

        jobs = [(c, b, order, args.top_samples, 7919 * c + b) for c in range(169) for b in range(TOP_BUCKETS)]
        eq_top = [[0.0] * TOP_BUCKETS for _ in range(169)]
        for cls, b, eq in pool.imap_unordered(_eq_vs_top, jobs, chunksize=16):
            eq_top[cls][b] = eq

    out = ROOT / "scaffold" / "pokerbot" / "core" / "preflop_tables.py"
    lines = [
        '"""GENERATED by tools/gen_preflop_tables.py - do not edit by hand.',
        "",
        f"Monte Carlo samples: {args.samples} per EQ_VS_RANDOM cell, {args.top_samples} per EQ_VS_TOP cell.",
        "Class indices follow pokerbot.core.cards.class_index.",
        '"""',
        "",
        "# HAND_ORDER: the 169 classes, strongest first.",
        "HAND_ORDER = [" + ", ".join(str(c) for c in order) + "]",
        "# names for reference: " + " ".join(class_name(c) for c in order[:40]) + " ...",
        "",
        "# EQ_VS_RANDOM[class][k-1]: equity vs k random hands (k = 1..5).",
        "EQ_VS_RANDOM = [",
    ]
    for c in range(169):
        lines.append("    [" + ", ".join(f"{v:.4f}" for v in eq_random[c]) + f"],  # {class_name(c)}")
    lines += [
        "]",
        "",
        f"# EQ_VS_TOP[class][b]: heads-up equity vs the top (2*(b+1))% of HAND_ORDER, {TOP_BUCKETS} buckets.",
        "EQ_VS_TOP = [",
    ]
    for c in range(169):
        lines.append("    [" + ", ".join(f"{v:.3f}" for v in eq_top[c]) + f"],  # {class_name(c)}")
    lines.append("]")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
