"""Random-search tuning of a zoo archetype's parameters (dev only).

    python tools/tune_archetype.py --base z_tag_chart --pool house:call --pool house:random \
        --pool house:allin --pool house:checkfold --out z_house_overfit_tag --trials 32

Mirrors how real teams iterate: the archetype is tuned only against the given
pool (e.g. the house bots) and saved as a new archetype file.
"""

from __future__ import annotations

import argparse
import ast
import random
import sys
from multiprocessing import Pool
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from testing.arena import expand_pool, run_table  # noqa: E402

ARCH = ROOT / "zoo" / "archetypes"
SPACE = {
    "looseness": (0.6, 1.7),
    "value_t": (0.6, 0.9),
    "bet_size": (0.4, 1.2),
    "call_margin": (-0.05, 0.12),
    "bluff_freq": (0.0, 0.2),
    "cbet_freq": (0.2, 1.0),
    "allin_margin": (-0.05, 0.1),
    "allin_assumed_top": (0.05, 0.5),
}


def base_params(name: str) -> dict:
    tree = ast.parse((ARCH / f"{name}.py").read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and getattr(node.targets[0], "id", "") == "PARAMS":
            return ast.literal_eval(node.value)
    return {}


def write_bot(path: Path, params: dict, doc: str, name: str) -> None:
    path.write_text(
        f'"""{doc}\n\nZoo opponent (dev only), generated by tools/tune_archetype.py.\n"""\n\n'
        f"from zcore.rulebot import RuleBot\n\nPARAMS = {params!r}\n\nbot = RuleBot(PARAMS, name={name!r})\n",
        encoding="utf-8",
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", required=True)
    ap.add_argument("--pool", action="append", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--trials", type=int, default=24)
    ap.add_argument("--tables", type=int, default=8)
    ap.add_argument("--seed", default="tune")
    args = ap.parse_args()

    pool = expand_pool(args.pool)
    base = base_params(args.base)
    rng = random.Random(args.seed)
    cands = [dict(base)]
    for _ in range(args.trials - 1):
        p = dict(base)
        for k, (lo, hi) in SPACE.items():
            p[k] = round(lo + (hi - lo) * rng.random(), 3)
        cands.append(p)
    tables = [[rng.choice(pool) for _ in range(4)] for _ in range(args.tables)]
    jobs = []
    for i, p in enumerate(cands):
        path = ARCH / f"_tune_{i}.py"
        write_bot(path, p, "tuning candidate", f"tune{i}")
        rel = str(path.relative_to(ROOT)).replace("\\", "/")
        for t, opps in enumerate(tables):
            jobs.append({"table": t, "cand": i, "specs": [rel] + opps, "seed": f"{args.seed}-{t}", "deals": 100})
    try:
        with Pool(8) as workers:
            res = workers.map(run_table, jobs, chunksize=2)
    finally:
        for i in range(len(cands)):
            (ARCH / f"_tune_{i}.py").unlink(missing_ok=True)
    score = [0.0] * len(cands)
    for r in res:
        score[r["cand"]] += sum(g[0] for g in r["points"]) / len(r["points"]) / args.tables
    best = max(range(len(cands)), key=lambda i: score[i])
    print(f"base score {score[0]:.3f}, best {score[best]:.3f} (trial {best})")
    write_bot(ARCH / f"{args.out}.py", cands[best],
              f"A12 {args.base} tuned only against {args.pool} (mirrors teams iterating vs house bots).", args.out)
    print(f"wrote {args.out}.py with {cands[best]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
